# Generated by Django 5.2.17 on 2026-10-06 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sme', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoteColeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adaptador', models.CharField(max_length=30)),
                ('agravo', models.CharField(max_length=30)),
                ('url_origem', models.URLField(max_length=2000)),
                ('territorio_codigo', models.CharField(max_length=7)),
                ('sha256', models.CharField(max_length=64)),
                ('dados_brutos', models.JSONField()),
                ('quantidade_registros', models.PositiveIntegerField()),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('fonte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='sme.fonteepidemiologica')),
            ],
        ),
        migrations.CreateModel(
            name='ExecucaoColeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('executando', 'Executando'), ('sucesso', 'Sucesso'), ('vazia', 'Sem registros'), ('erro', 'Falha')], max_length=15)),
                ('iniciada_em', models.DateTimeField(auto_now_add=True)),
                ('finalizada_em', models.DateTimeField(null=True)),
                ('mensagem', models.CharField(blank=True, max_length=300)),
                ('quantidade_registros', models.PositiveIntegerField(default=0)),
                ('repetida', models.BooleanField(default=False)),
                ('origem', models.CharField(default='manual', max_length=15)),
                ('fonte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coletas', to='sme.fonteepidemiologica')),
                ('lote', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sme.lotecoleta')),
            ],
            options={
                'ordering': ['-iniciada_em', '-pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='lotecoleta',
            constraint=models.UniqueConstraint(fields=('fonte', 'sha256'), name='lote_fonte_hash_unique'),
        ),
        migrations.AddConstraint(
            model_name='execucaocoleta',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'executando')), fields=('fonte',), name='uma_coleta_ativa_por_fonte'),
        ),
    ]
